version: "3.8"
services:
  forntend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src
    environment:
      - NODE_ENV=local
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      target: api
      args:
        user: laravel
        uid: 1000
    # command: sh -c "./wait-for-it.sh mysql:3306 -t 30 && ./wait-for-it.sh redis:6379 -t 30 && php-fpm"
    depends_on:
      - mysql
      - redis
      - migrate
    restart: unless-stopped
    volumes:
      - ./api:/usr/src

  redis:
    image: redis:8.0-rc1-alpine
    restart: unless-stopped
    volumes:
      - ./redisdata:/data
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.4.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./deployment/config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./deployment/config/mysql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - "3306:3306"
  migrate:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        user: laravel
        uid: 1000
    # command: sh -c "./wait-for-it.sh mysql:3306 -t 30 && php /usr/src/artisan migrate --force"
    restart: no
    depends_on:
      - mysql

  nginx:
    build:
      context: .
      dockerfile: ./api/Dockerfile.nginx
    restart: unless-stopped
    volumes:
      - ./api:/usr/src
      - ./deployment/config/nginx/nginx-api.conf:/etc/nginx/nginx.conf
    ports:
      - "9000:80"
    depends_on:
      - api
